// Environment configuration injected at build time
window.FIREBASE_API_KEY = '__FIREBASE_API_KEY__';
window.FIREBASE_AUTH_DOMAIN = '__FIREBASE_AUTH_DOMAIN__';
window.FIREBASE_PROJECT_ID = '__FIREBASE_PROJECT_ID__';
window.FIREBASE_STORAGE_BUCKET = '__FIREBASE_STORAGE_BUCKET__';
window.FIREBASE_MESSAGING_SENDER_ID = '__FIREBASE_MESSAGING_SENDER_ID__';
window.FIREBASE_APP_ID = '__FIREBASE_APP_ID__';
window.CAFE24_SHOP_ID = '__CAFE24_SHOP_ID__';
